theme = "hugo-base16-theme"
baseURL = "https://hobo0xcc.github.io/Blog/"
languageCode = "en-us"
title = "Hobo"
canonifyurls = true
publishdir = "public"
disqusShortname = "Hobo"

[params]
    body_classes = "Noto Sans JP"