# config.toml

publishdir = "../docs"

baseURL = "https://hobo0xcc.github.io/Blog"
languageCode = "ja-jp"
defaultContentLanguage = "ja"

title = "0xcc"
copyright = "Copyright (c) 2020, all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
math = true

googleAnalytics = ""
disqusShortname = ""

[author]
  name = ""

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "monokai" # dark themes: monokai, api, fruity, native, rrt, swapoff

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about"
[[menu.main]]
  name = "Memo"
  weight = -90
  identifier = "memo"
  url = "/memo"

[params.meta]
  keywords = ""
  description = ""

[params]
  github = "hobo0xcc"
  gitlab = ""
  twitter = "hobo0xcc"
  linkedin = ""
  email = ""
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
  utterancesRepo="" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="" # Default: pathname
