# config.toml

publishdir = "../docs"

baseURL = "https://hobo0xcc.github.io/Blog"
defaultContentLanguage = "ja"
languageCode = "ja-JP"

canonifyurls = true
copyright = "Copyright (c) 2021, all rights reserved."
math = true
paginate = 3
theme = "hugo-dusk"
title = "0xb109"

disqusShortname = ""
googleAnalytics = ""

[author]
name = ""

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
[markup.highlight]
style = "monokai" # dark themes: monokai, api, fruity, native, rrt, swapoff
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = -120

[[menu.main]]
identifier = "tag"
name = "Tags"
url = "/tags/"
weight = -110
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = -100
[[menu.main]]
identifier = "memo"
name = "Memo"
url = "/memo"
weight = -90

[params.meta]
description = ""
keywords = ""

[params]
customCSS = ["css/style.css"] 
email = "" 
github = "hobo0xcc" 
gitlab = "" 
linkedin = "" 
theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
twitter = "hobo0xcc" 
utterancesIssueTerm = "" # Default: pathname
utterancesRepo = "" # Utterances is enabled when this param is set
utterancesTheme = "github-dark" # Default: github-dark
